# Generated by .github/workflows/release.yml on each v* tag — do not hand-edit.
class Lakeleto < Formula
  desc "Instant local lakehouse-table explorer (Parquet/CSV/Iceberg) in a single binary"
  homepage "https://github.com/lucheeseng827/lakeleto"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/lucheeseng827/lakeleto/releases/download/v#{version}/lakeleto-aarch64-apple-darwin.tar.gz"
      sha256 "9bc587e486aae6e33907482b5f4b5ef21c23d5f254f716ca741a48bc03db5e92"
    end
    on_intel do
      url "https://github.com/lucheeseng827/lakeleto/releases/download/v#{version}/lakeleto-x86_64-apple-darwin.tar.gz"
      sha256 "15225a8409ae77053e0c521d9d2957eac51d90c7447e2c715f36a97a2bacaec5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lucheeseng827/lakeleto/releases/download/v#{version}/lakeleto-aarch64-unknown-linux-musl.tar.gz"
      sha256 "07929823a56775a8528e5a578aa1c399d5fdc73c0348d3f720f91fbb29e53862"
    end
    on_intel do
      url "https://github.com/lucheeseng827/lakeleto/releases/download/v#{version}/lakeleto-x86_64-unknown-linux-musl.tar.gz"
      sha256 "df8bd38b245459b1ca84dc4aaab7d608aa8d7716406f65f5711811cdc85fb0ac"
    end
  end

  def install
    bin.install "lakeleto"
  end

  test do
    assert_match "lakeleto", shell_output("#{bin}/lakeleto --help")
  end
end
