# Generated by .github/workflows/release.yml on each v* tag — do not hand-edit.
class Lakeleto < Formula
  desc "Instant local lakehouse-table explorer (Parquet/CSV/Iceberg) in a single binary"
  homepage "https://github.com/lucheeseng827/lakeleto"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/lucheeseng827/lakeleto/releases/download/v#{version}/lakeleto-aarch64-apple-darwin.tar.gz"
      sha256 "24ab681ccc72954e167d9f864907ed83ffb4f822fcd012c4700047a039b25987"
    end
    on_intel do
      url "https://github.com/lucheeseng827/lakeleto/releases/download/v#{version}/lakeleto-x86_64-apple-darwin.tar.gz"
      sha256 "7a825d63bae241f9590bc0f9d5ae0ac80d444a06ca921eba32ec3a3947385277"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lucheeseng827/lakeleto/releases/download/v#{version}/lakeleto-aarch64-unknown-linux-musl.tar.gz"
      sha256 "d85cb6908ecc7921f75dea70671c0427099dfbb606199461c36ac744a8db8c5d"
    end
    on_intel do
      url "https://github.com/lucheeseng827/lakeleto/releases/download/v#{version}/lakeleto-x86_64-unknown-linux-musl.tar.gz"
      sha256 "06c7e9ab8f72889607dadc72d21ad6fb916d64cf6e416ad2543a46ade9f3c2dc"
    end
  end

  def install
    bin.install "lakeleto"
  end

  test do
    assert_match "lakeleto", shell_output("#{bin}/lakeleto --help")
  end
end
