# Generated by .github/workflows/release.yml on each v* tag — do not hand-edit.
class Lakeleto < Formula
  desc "Instant local lakehouse-table explorer (Parquet/CSV/Iceberg) in a single binary"
  homepage "https://github.com/lucheeseng827/lakeleto"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/lucheeseng827/lakeleto/releases/download/v#{version}/lakeleto-aarch64-apple-darwin.tar.gz"
      sha256 "ddd6ffab0c60c31d9fbeec1c38b1706ff006350350cc2ef06309385425430c5d"
    end
    on_intel do
      url "https://github.com/lucheeseng827/lakeleto/releases/download/v#{version}/lakeleto-x86_64-apple-darwin.tar.gz"
      sha256 "5c84e990dd0d1afcd5b1e1cb353e7dac159569b6f90f81e07eed382eeeef7221"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lucheeseng827/lakeleto/releases/download/v#{version}/lakeleto-aarch64-unknown-linux-musl.tar.gz"
      sha256 "fbe1cd50a6e4e48954a8205878ec29ce910fd5994cb54f17801d4879a9b7c5b4"
    end
    on_intel do
      url "https://github.com/lucheeseng827/lakeleto/releases/download/v#{version}/lakeleto-x86_64-unknown-linux-musl.tar.gz"
      sha256 "7ce74c1d15b9e2e6e4854def3c514167c2483369220dddc779d55192e2d1a115"
    end
  end

  def install
    bin.install "lakeleto"
  end

  test do
    assert_match "lakeleto", shell_output("#{bin}/lakeleto --help")
  end
end
